### ISSUE TITLE
Not Found [IP: 101.6.15.130 80]

### ISSUE THREAD

**Issue by qinwenzhou** [soulteary/docker-gfpgan#3]
你好！非常感谢你分享了这么优秀的内容。但我按照你说的方法，在腾讯云服务器中使用docker编译，却收到了如下的错误。
编译命令：docker build -t soulteary/docker-gfpgan .
收到错误：
Step 5/10 : RUN apt install -y curl &&     curl -L "https://github.com/xinntao/facexlib/releases/download/v0.1.0/detection_Resnet50_Final.pth" -o "/opt/conda/lib/python3.9/site-packages/facexlib/weights/detection_Resnet50_Final.pth" &&     apt remove -y curl
 ---> Running in 3842eac08f50

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libcurl4
The following NEW packages will be installed:
  curl libcurl4
0 upgraded, 2 newly installed, 0 to remove and 4 not upgraded.
Need to get 608 kB of archives.
After this operation, 1186 kB of additional disk space will be used.
Err:1 http://mirrors.tuna.tsinghua.edu.cn/debian bullseye/main amd64 libcurl4 amd64 7.74.0-1.3+deb11u1
  404  Not Found [IP: 101.6.15.130 80]
Err:2 http://mirrors.tuna.tsinghua.edu.cn/debian bullseye/main amd64 curl amd64 7.74.0-1.3+deb11u1
  404  Not Found [IP: 101.6.15.130 80]
E: Failed to fetch http://mirrors.tuna.tsinghua.edu.cn/debian/pool/main/c/curl/libcurl4_7.74.0-1.3%2bdeb11u1_amd64.deb  404  Not Found [IP: 101.6.15.130 80]
E: Failed to fetch http://mirrors.tuna.tsinghua.edu.cn/debian/pool/main/c/curl/curl_7.74.0-1.3%2bdeb11u1_amd64.deb  404  Not Found [IP: 101.6.15.130 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt install -y curl &&     curl -L "https://github.com/xinntao/facexlib/releases/download/v0.1.0/detection_Resnet50_Final.pth" -o "/opt/conda/lib/python3.9/site-packages/facexlib/weights/detection_Resnet50_Final.pth" &&     apt remove -y curl' returned a non-zero code: 100

**Comment by soulteary** [comment]
可以参考最新的教程，模型下载的麻烦事应该就没有了。:D
